targets:
    $default:
        builders:
            source_gen|combining_builder:
                generate_for:
                    - lib/**.dart
                options:
                    build_extensions:
                        '^lib/data/models/{{}}.dart': 'lib/data/models/generated/{{}}.g.dart'
